---
version: 0.1.0
hassio_api: true
slug: nginx_proxy
name: NGINX Home Assistant SSL proxy + AW
description: An SSL/TLS proxy with Authenticated Webview support
url: https://github.com/yannicklarrivee/homeassistant-addons-master
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: homeassistant/{arch}-addon-nginx_proxy
init: false
map:
  - ssl
  - share
options:
  domain: null
  homeassistant: homeassistant
  homeassistant_port: 8123
  oauth2_proxy: homeassistant
  oauth2_proxy_port: 4180
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  443/tcp: 443
  80/tcp: null
schema:
  domain: str
  homeassistant: str
  homeassistant_port: int
  oauth2_proxy: str
  oauth2_proxy_port: int
  certfile: str
  keyfile: str
