version: 2.1
orbs:
  docker: circleci/docker@2.1.3
workflows:
  build-and-publish-addons-images:
    jobs:
      - docker/publish:
          after_build:
            - run:
                command: echo "Did this after the build"
                name: Do this after the build
          after_checkout:
            - run:
                command: echo "Did this after checkout" & pwd & ls
                name: Do this after checkout
          before_build:
            - run:
                command: echo "Change directory" & ls & cd $CIRCLE_WORKING_DIRECTORY/dropbox-autodelete & pwd
                name: Change directory
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/dropbox-autodelete
          path: $CIRCLE_WORKING_DIRECTORY/dropbox-autodelete