version: 2.1
executors:
  arm-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
orbs:
  docker: circleci/docker@2.1.3
  yq: nikkei/rnikkei-yq@0.0.3
jobs:
  install-yq:
    executor: arm-executor
    steps:
     - yq/install 
workflows:
  build-and-publish-addons-images:
    jobs:
      - install-yq
      - docker/publish:
          name: Publish dropbox-autodelete addon
          image: $DOCKER_LOGIN/dropbox-autodelete
          path: dropbox-autodelete
          docker-context: dropbox-autodelete
      - docker/publish:
          name: Publish oauth2-proxy addon
          image: $DOCKER_LOGIN/oauth2-proxy
          path: oauth2-proxy
          docker-context: oauth2-proxy
      - docker/publish:
          name: Publish tshark addon
          image: $DOCKER_LOGIN/tshark
          path: tshark
          docker-context: tshark
      - docker/publish:
          matrix:
            parameters:
              path: [rtl4332mqtt-interlogix-autodiscovery,tshark]
          context:
            - build-architecture
          pre-steps:
            - checkout
            - run:
                command: echo 'export ARCH=armv7' >> "$BASH_ENV"
            - run:
                command: echo 'export PLATFORM=$(cat ./<< matrix.path >>/build.yml | yq ''.platform.[env(ARCH)]'')' >> "$BASH_ENV"
            - checkout
            - run:
                command: echo 'export TAG=$(cat ./<< matrix.path >>/config.yml | yq '\'.version\''')' >> "$BASH_ENV"
            - run:
                command: echo $ARCH && echo $PLATFORM && echo $TAG
          name: Publish $ARCH-<< matrix.path >> addon
          before_build:
            - checkout
            - run:
                command: ARCH=armv7 && pwd && ls -ahl && PLATFORM=$(cat ./<< matrix.path >>/build.yml | yq '.platform.[env(ARCH)]') && echo $ARCH && echo $PLATFORM
            - checkout
            - run:
                command: TAG=$(cat ./<< matrix.path >>/config.yml | yq '.version') && echo $TAG  
          image: $DOCKER_LOGIN/$ARCH-<< matrix.path >>
          extra_build_args: --build-arg BUILD_FROM=ghcr.io/home-assistant/$ARCH-base:latest --platform $PLATFORM
          executor: arm-executor
          docker-context: << matrix.path >>
          tag: $TAG
      - docker/publish:
          name: Publish nginx_proxy addon
          image: $DOCKER_LOGIN/armv7-nginx_proxy
          path: nginx_proxy
          docker-context: nginx_proxy