version: 2.1
orbs:
  docker: circleci/docker@2.1.3
workflows:
  build-and-publish-addons-images:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/dropbox-autodelete
          path: dropbox-autodelete
          docker-context: dropbox-autodelete