version: 2.1
orbs:
  docker: circleci/docker@2.1.3
jobs:
  build-and-publish-dropbox-autodelete-image:
    executor: docker/docker
    steps:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/dropbox-autodelete    
workflows:
  build-and-publish-addons-images:
    jobs:
      - build-and-publish-dropbox-autodelete-image