version: 2.1
orbs:
  docker: circleci/docker@2.1.3
workflows:
  build-and-publish-addons-images:
    jobs:
      - docker/publish:
          name: Publish dropbox-autodelete addon
          image: $DOCKER_LOGIN/dropbox-autodelete
          path: dropbox-autodelete
          docker-context: dropbox-autodelete
      - docker/publish:
          name: Publish oauth2-proxy addon
          image: $DOCKER_LOGIN/oauth2-proxy
          path: oauth2-proxy
          docker-context: oauth2-proxy
      - docker/publish:
          name: Publish tshark addon
          image: $DOCKER_LOGIN/tshark
          path: tshark
          docker-context: tshark
      - docker/publish:
          name: Publish armv7-rtl4332mqtt-interlogix-autodiscovery addon
          image: $DOCKER_LOGIN/armv7-rtl4332mqtt-interlogix-autodiscovery
          extra_build_args: --buid-from ghcr.io/home-assistant/armv7-base:3.14 --platform armv7
          path: rtl4332mqtt-interlogix-autodiscovery
          docker-context: rtl4332mqtt-interlogix-autodiscovery
          tag: 0.2.8
      - docker/publish:
          name: Publish nginx_proxy addon
          image: $DOCKER_LOGIN/armv7-nginx_proxy
          path: nginx_proxy
          docker-context: nginx_proxy