name: 'Dropbox autodelete'
version: 0.1.0
slug: dropbox-autodelete
description: 'Autodelete files in dropbox folder (Keep X last enrties)'
url: 'https://github.com/yannicklarrivee/homeassistant-addons-master'
startup: once
boot: manual
init: 'false'
map:
    - 'config:rw'
    - ssl
usb: true
host_network: 'False'
arch:
    - aarch64
    - amd64
    - armv7
    - i386
options:
    access_token: MY_ACCESS_TOKEN
    path: backup/
    number_of_files: 10
schema:
    access_token: str
    path: str
    number_of_files: int
