name: voipms-mms
version: 0.4.0
slug: voipms-mms
description: 'Start voipms-mms service to send a sms.'
url: 'https://github.com/yannicklarrivee/homeassistant-addons-master'
startup: application
boot: auto
init: false
stdin: true
hassio_api: true
hassio_role: default
homeassistant_api: true
map:
    - config
    - 'share:rw'
host_network: 'true'
arch:
    - aarch64
    - amd64
    - armv7
    - i386
image: yannicklarrivee/{arch}-voipms-mms
options:
    api_username: xxxxxxxx
    api_password: xxxxxxxxx
    did: xxxxxxx
schema:
    api_username: str
    api_password: str
    did: str
