name: tshark
version: 0.5.0
slug: tshark
description: 'Monitor network with tshark'
url: 'https://github.com/yannicklarrivee/homeassistant-addons-master'
startup: once
boot: manual
map:
    - config
    - 'share:rw'
usb: true
host_network: 'true'
privileged:
    - NET_ADMIN
arch:
    - aarch64
    - amd64
    - armv7
    - i386
options:
    interface: eth0
    filter: 'host homeassistant.local'
    pcap_file: homeassistant.pcap
    autostop: 'duration:60'
schema:
    interface: str
    filter: str
    pcap_file: str
    autostop: str
