name: 'Dropbox Sync'
version: 0.0.13
slug: dropbox_sync
description: 'Upload your Hass.io backups to Dropbox'
url: 'https://github.com/yannicklarrivee/homeassistant-addons-master'
startup: before
homeassistant_api: true
init: 'false'
arch:
    - aarch64
    - amd64
    - armv7
    - i386
stdin: true
hassio_api: true
hassio_role: default
boot: auto
map:
    - backup
    - share
options:
    oauth_access_token: '<YOUR_ACCESS_TOKEN>'
    output: ""
schema:
    oauth_access_token: str
    output: str
    keep_last: 'int(0,)?'
    filetypes: 'str?'
image: 'yannicklarrivee/{arch}-dropbox-sync'
